@file:Suppress("ktlint:standard:filename")

package app.ledger.finance.domain

/** Frozen cross-layer standard shared by domain rules, database audits, and restore validation. */
enum class PermanentInvariant(val id: String) {
    JOURNAL_BALANCED("INV-001"),
    POSTING_CURRENCY_MATCHES_ACCOUNT("INV-002"),
    SINGLE_CLASSIFICATION_PROJECT_AND_GOAL("INV-003"),
    ORDINARY_TRANSACTION_SINGLE_PRIMARY_AMOUNT("INV-004"),
    CURRENT_REVISION_SELF_CONSISTENT("INV-005"),
    HISTORICAL_FACTS_IMMUTABLE("INV-006"),
    APPLY_REVERSED_AT_MOST_ONCE("INV-007"),
    ACTIVE_TRANSACTION_HAS_ONE_CURRENT_EFFECT("INV-008"),
    TRASHED_TRANSACTION_HAS_ZERO_CURRENT_EFFECT("INV-009"),
    REFUND_WITHIN_REFUNDABLE_BALANCE("INV-010"),
    REFUND_DATES_ARE_INDEPENDENT("INV-011"),
    CREDIT_PAYMENT_HAS_NO_INCOME_OR_EXPENSE("INV-012"),
    LOAN_PRINCIPAL_PAYMENT_HAS_NO_EXPENSE("INV-013"),
    LOAN_COST_COMPONENTS_ARE_NON_CONSUMPTION_EXPENSE("INV-014"),
    INTERNAL_TRANSFER_PRESERVES_NET_FINANCIAL_ASSETS("INV-015"),
    CURRENT_FX_DOES_NOT_REWRITE_HISTORY("INV-016"),
    CURRENT_REVALUATION_IS_NOT_INCOME_OR_EXPENSE("INV-017"),
    ROOT_BUDGETS_FIT_TOTAL("INV-018"),
    CHILD_BUDGETS_FIT_PARENT("INV-019"),
    BUDGET_ROLLOVER_IS_REBUILDABLE("INV-020"),
    GOAL_BALANCE_DOES_NOT_CHANGE_ACCOUNT_BALANCE("INV-021"),
    SETTLEMENT_POSITIONS_SUM_TO_ZERO("INV-022"),
    EXTERNAL_SETTLEMENT_DOES_NOT_CHANGE_LOCAL_ACCOUNT("INV-023"),
    COMPLETED_SETTLEMENT_HISTORY_IS_IMMUTABLE("INV-024"),
    LOAN_SCHEDULE_PRINCIPAL_CONSERVES("INV-025"),
    INSTALLMENT_SCHEDULE_PRINCIPAL_CONSERVES("INV-026"),
    RECURRENCE_OCCURRENCE_IS_UNIQUE("INV-027"),
    CANDIDATE_HAS_NO_FORMAL_FINANCIAL_EFFECT("INV-028"),
    ARCHIVE_AND_TOMBSTONE_PRESERVE_HISTORY("INV-029"),
    PURGE_TOMBSTONE_WINS_MERGE_RESTORE("INV-030"),
    CORE_PROJECTIONS_SHARE_LOCAL_REVISION("INV-031"),
    VAULT_FIELDS_ARE_ISOLATED("INV-032"),
    LARGE_OPERATION_FAILURE_IS_ATOMIC("INV-033"),
    MONEY_ACCUMULATION_DETECTS_OVERFLOW("INV-034"),
    CONTENT_DEPENDENT_CACHES_ARE_VERSIONED("INV-035"),
    ;

    companion object {
        val ids: Set<String> = entries.mapTo(linkedSetOf(), PermanentInvariant::id)
    }
}
