#!/usr/bin/env python3
"""Generate P04 Kotlin contracts and the token-only screenshot golden.

The generator has an explicit textual-input allowlist. It does not enumerate or open any
visual-review material. The PNG it writes is newly derived from JSON color tokens only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import zlib
from pathlib import Path
from typing import Any, Iterable

import yaml


ROOT = Path(__file__).resolve().parents[1]
UI_ROOT = ROOT / "docs/初始开发文件存档/UI设计稿与实现契约_v1.0"
TOKEN_SOURCE = UI_ROOT / "android_ledger_ui_tokens_v1.json"
SCREEN_SOURCE = UI_ROOT / "android_ledger_screen_contract_v1.yaml"
TOKEN_OUTPUT = (
    ROOT
    / "core/designsystem/src/main/kotlin/app/ledger/core/designsystem/tokens/GeneratedLedgerTokenContract.kt"
)
SCREEN_OUTPUT = (
    ROOT
    / "core/navigation/src/main/kotlin/app/ledger/core/navigation/GeneratedScreenContract.kt"
)
GOLDEN_OUTPUT = ROOT / "core/designsystem/src/androidTest/assets/goldens/p04_token_palette.png"


def canonical_hash(value: Any) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def scalar_paths(value: Any, path: str = "") -> Iterable[tuple[str, Any]]:
    if isinstance(value, dict):
        for key, item in value.items():
            child = f"{path}.{key}" if path else str(key)
            yield from scalar_paths(item, child)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from scalar_paths(item, f"{path}[{index}]")
    else:
        yield path, value


def kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False).replace("$", "\\$")


def joined(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return " | ".join(str(item) for item in value)
    return str(value)


def render_token_contract(tokens: dict[str, Any]) -> str:
    entries = list(scalar_paths(tokens))
    body = "\n".join(
        f"        {kotlin_string(path)} to {kotlin_string(json.dumps(value, ensure_ascii=False, separators=(',', ':')))},"
        for path, value in entries
    )
    return f"""// Generated by scripts/generate_p04_contracts.py. Do not edit manually.
package app.ledger.core.designsystem.tokens

/** Complete scalar projection of the frozen JSON token contract. */
public object GeneratedLedgerTokenContract {{
    public const val VERSION: String = {kotlin_string(tokens['meta']['version'])}
    public const val SCALAR_COUNT: Int = {len(entries)}
    public const val CANONICAL_SHA256: String = {kotlin_string(canonical_hash(tokens))}

    public val scalarValues: Map<String, String> = linkedMapOf(
{body}
    )
}}
"""


def parameter_kind(raw: str) -> tuple[str, bool, list[str]]:
    name, declared = raw.split(":", 1)
    optional = declared.endswith("?")
    value_type = declared.removesuffix("?")
    if value_type == "StableId":
        kind = "STABLE_ID"
        choices: list[str] = []
    elif value_type == "YYYYMM":
        kind = "YEAR_MONTH"
        choices = []
    elif value_type == "String":
        kind = "OPAQUE_KEY"
        choices = []
    elif value_type == "enumMask":
        kind = "ENUM_MASK"
        choices = []
    elif value_type == "Int":
        kind = "POSITIVE_INT"
        choices = []
    elif value_type == "WidgetType":
        kind = "NAMED_ENUM"
        choices = []
    elif "|" in value_type or value_type.isupper():
        kind = "ENUM"
        choices = value_type.split("|")
    else:
        raise ValueError(f"unsupported route parameter type {raw!r}")
    return kind, optional, choices


def render_string_list(values: list[str], indent: int) -> str:
    if not values:
        return "emptyList()"
    prefix = " " * indent
    content = ",\n".join(f"{prefix}    {kotlin_string(value)}" for value in values)
    return f"listOf(\n{content},\n{prefix})"


def render_screen_contract(document: dict[str, Any]) -> str:
    screens = document["screens"]
    blocks: list[str] = []
    for screen in screens:
        params: list[str] = []
        for raw in screen["params"]:
            name = raw.split(":", 1)[0]
            kind, optional, choices = parameter_kind(raw)
            params.append(
                "ScreenParameterSpec("
                f"name = {kotlin_string(name)}, kind = RouteArgumentKind.{kind}, optional = {str(optional).lower()}, "
                f"allowedValues = {render_string_list(choices, 16)}"
                ")"
            )
        param_block = "emptyList()" if not params else "listOf(\n" + ",\n".join(
            f"                {value}" for value in params
        ) + ",\n            )"
        result = "null" if screen["result"] is None else kotlin_string(str(screen["result"]))
        blocks.append(
            "        ScreenContract(\n"
            f"            screenId = ScreenId({kotlin_string(screen['id'])}),\n"
            f"            group = {kotlin_string(screen['group'])},\n"
            f"            module = {kotlin_string(screen['module'])},\n"
            f"            routePattern = {kotlin_string(screen['route'])},\n"
            f"            title = {kotlin_string(screen['title'])},\n"
            f"            presentation = LedgerPresentation.{str(screen['presentation']).upper()},\n"
            f"            parameters = {param_block},\n"
            f"            resultType = {result},\n"
            f"            requiredStates = {render_string_list(screen['requiredStates'], 12)},\n"
            f"            primaryComponents = {render_string_list(screen['primaryComponents'], 12)},\n"
            f"            notes = {render_string_list(screen['notes'], 12)},\n"
            "        )"
        )
    body = ",\n".join(blocks)
    return f"""// Generated by scripts/generate_p04_contracts.py. Do not edit manually.
@file:Suppress("LargeClass")

package app.ledger.core.navigation

public object GeneratedScreenContract {{
    public const val VERSION: String = {kotlin_string(document['meta']['version'])}
    public const val SCREEN_COUNT: Int = {len(screens)}
    public const val REQUIRED_STATE_COUNT: Int = {sum(len(screen['requiredStates']) for screen in screens)}
    public const val CANONICAL_SHA256: String = {kotlin_string(canonical_hash(screens))}

    public val navigationRules: List<String> = {render_string_list(document['meta']['navigationRules'], 4)}

    public val screens: List<ScreenContract> = listOf(
{body},
    )
}}
"""


def hex_rgba(value: str) -> tuple[int, int, int, int]:
    raw = value.removeprefix("#")
    if len(raw) == 6:
        raw += "FF"
    if len(raw) != 8:
        raise ValueError(f"unsupported color {value!r}")
    return tuple(int(raw[index : index + 2], 16) for index in range(0, 8, 2))  # type: ignore[return-value]


def golden_colors(tokens: dict[str, Any]) -> list[str]:
    color = tokens["color"]
    values: list[str] = []
    for mode in ("light", "dark"):
        values.extend(value for value in color[mode].values() if isinstance(value, str) and value.startswith("#"))
    for semantic in color["semantic"].values():
        for mode in ("light", "dark"):
            values.extend(value for value in semantic[mode].values() if isinstance(value, str) and value.startswith("#"))
    for palette in color["categoryPalette"]:
        values.extend(value for key, value in palette.items() if key != "id")
    for value in color["chart"].values():
        if isinstance(value, list):
            values.extend(value)
        else:
            values.append(value)
    return values


def png_chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)


def render_golden(tokens: dict[str, Any]) -> bytes:
    colors = golden_colors(tokens)
    background = hex_rgba(tokens["color"]["light"]["background"])
    cell = 8
    columns = 16
    rows = (len(colors) + columns - 1) // columns
    width = columns * cell
    height = rows * cell
    pixels = bytearray()
    for y in range(height):
        pixels.append(0)
        for x in range(width):
            index = (y // cell) * columns + (x // cell)
            rgba = hex_rgba(colors[index]) if index < len(colors) else background
            alpha = rgba[3]
            composited = tuple(
                (rgba[channel] * alpha + background[channel] * (255 - alpha) + 127) // 255
                for channel in range(3)
            )
            pixels.extend((*composited, 255))
    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", header) + png_chunk(
        b"IDAT", zlib.compress(bytes(pixels), level=9)
    ) + png_chunk(b"IEND", b"")


def write_if_changed(path: Path, content: str | bytes) -> None:
    encoded = content.encode("utf-8") if isinstance(content, str) else content
    if path.is_file() and path.read_bytes() == encoded:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)


def outputs(tokens: dict[str, Any], screens: dict[str, Any]) -> dict[Path, bytes]:
    return {
        TOKEN_OUTPUT: render_token_contract(tokens).encode("utf-8"),
        SCREEN_OUTPUT: render_screen_contract(screens).encode("utf-8"),
        GOLDEN_OUTPUT: render_golden(tokens),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when checked-in generated outputs differ")
    args = parser.parse_args()
    tokens = json.loads(TOKEN_SOURCE.read_text(encoding="utf-8"))
    screens = yaml.safe_load(SCREEN_SOURCE.read_text(encoding="utf-8"))
    expected = outputs(tokens, screens)
    if args.check:
        drifted = [str(path.relative_to(ROOT)) for path, content in expected.items() if not path.is_file() or path.read_bytes() != content]
        if drifted:
            raise SystemExit("P04 generated contract drift: " + ", ".join(drifted))
        print(
            "P04 generated contracts: PASS "
            f"token_scalars={len(list(scalar_paths(tokens)))} screens={len(screens['screens'])} "
            f"states={sum(len(screen['requiredStates']) for screen in screens['screens'])}"
        )
        return 0
    for path, content in expected.items():
        write_if_changed(path, content)
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
